### ISSUE TITLE
About batch_ size

### ISSUE THREAD

**Issue by Rouchestand** [joeyz0z/ConZIC#4]
Set caption_img_path to ./examples and batch_size to 2. Running run.py will result in the following error：
Traceback (most recent call last):
  File "run.py", line 162, in <module>
    run_control(run_type, args, img_dir, lm_model, lm_tokenizer, clip, token_mask)
  File "run.py", line 87, in run_control
    gen_texts, clip_scores = control_generate_caption(lm_model, clip, lm_tokenizer, image_instance, token_mask,
  File "/home/bishe/prc/ConZIC-main/ConZIC-main/control_gen_utils.py", line 200, in control_generate_caption
    generate_texts, clip_scores = sentiment_sequential_generation(model, clip, tokenizer, image_instance, token_mask, prompt,
  File "/home/bishe/prc/ConZIC-main/ConZIC-main/control_gen_utils.py", line 54, in sentiment_sequential_generation
    topk_inp[:, ii + seed_len] = idxs_
RuntimeError: The expanded size of the tensor (400) must match the existing size (200) at non-singleton dimension 0.  Target sizes: [400].  Tensor sizes: [200]

**Comment by joeyz0z** [comment]
Currently, our released code is a simple demo, only supporting batch_size=1, we will consider updating our released code in the future.

**Comment by Rouchestand** [comment]
Thank you for your warm answer. Looking forward to your code update

**Comment by Lxb-Code-Dev** [comment]
Can you tell me the batch-size value of the experiment in the paper?

**Comment by joeyz0z** [comment]
We set batch_size==1 in our paper.

**Comment by Lxb-Code-Dev** [comment]
Thank you for your reply.
